[features]
seeds = false
skip-lint = false
[programs.localnet]
homework13 = "GovAH137uoY4ifyfTNQjesKNJKo55tMF435dBfwZ22DG"

[programs.devnet]
homework13 = "GovAH137uoY4ifyfTNQjesKNJKo55tMF435dBfwZ22DG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
#cluster = "devnet"
wallet = "/home/kitan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
