[features]
seeds = false
skip-lint = false
[programs.localnet]
example1-lottery = "8nzsmfzo6591JyTajkpxfGvL8yzFtCuBqkSa14G627Jv"
example2-rps = "2J6MMLbHz4M3ZPvtZAqZrhA5AJn3WL68D9QdwXRXga2L"
example3-consortium = "AkdStj5UmLA6JHBkDmL9J5Qu6Uz1gYUf358o98Z81Pqs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/kitan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
